container:
  image: l.gcr.io/google/bazel:latest

test_193_task:
  test_script: 
    bazel build 
      --spawn_strategy=sandboxed
      --strategy=Javac=sandboxed
      --genrule_strategy=sandboxed
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
      --define=ij_product=intellij-2019.3
      //:ijwb_tests
      

