container:
  image: l.gcr.io/google/bazel:latest

test_all_task:
  env:
    matrix:
      - IJ_PRODUCT: intellij-2019.2
      - IJ_PRODUCT: intellij-2019.3

  test_script: 
    bazel test 
      --spawn_strategy=sandboxed
      --strategy=Javac=sandboxed
      --genrule_strategy=sandboxed
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST/$IJ_PRODUCT
      --define=ij_product=$IJ_PRODUCT
      //:ijwb_tests    

